FROM python:3.12-alpine

WORKDIR /data/qr-doc/

RUN pip install fastapi \
    && pip install uvicorn \
    && python -m pip install qrcode

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port",  "8000"]